### ISSUE TITLE
Triangle/Tetgen output do not provide internal Edges/Faces

### ISSUE THREAD

**Issue by pjacquet88** [MmgTools/mmg#100]
For the use of HDG  (Hybridizable Discontinuous Galerkin) in Hou10ni software, we may provide internal edges (in 2D) or faces (in 3D). However triangle/tetgen outputs from MMG do not provide this internal information.

Is it possible to export this information under the triangle/tetgen format in the .edge/.face files ?

**Comment by Algiane** [comment]
Hello,

I will add the list of the internal edges at Triangle format. These edges will be saved with the reference 0.

Just note that you will loose the possibility to differentiate internal edges from an internal boundary that shares two domains of same references (`opnbdy` mode) if this boundary has the reference 0.

**Comment by Algiane** [comment]
Hi @pjacquet88,

You can use the `feature/new-Triangle-output` to have Mmg outputs more consistent with the native Triangle ones:
  - the new `.poly` file contains the list of the boundary edges;
  - the `.edge` file contains the entire list of the mesh edges (boundary edges+internal ones);
  
Just note that I will not adapt the 3D output because the only possibility is to append the internal edges/faces to the `.edge` and `.face` files and I prefer keeping the default Tetgen file format.

It is not tested so I let you tell me if you have issue.

Regards,
Algiane
