### ISSUE TITLE
MMGS failing with various examples.

### ISSUE THREAD

**Issue by cbritopacheco** [MmgTools/mmg#168]
# Environment

|             |                           |
|--------| ---------------|
|    OS     | macOS Big Sur |
| Compiler | AppleClang 13.0.0.13000029 |
| mmg   |  95aabff3075f466e94bed25414922e0194241e05 |
| Build | Release |

# Problem

For a very simple test case, MMG fails in discretizing a surface subdomain. Given the following data:

[fault.mesh.txt](https://github.com/MmgTools/mmg/files/9971348/fault.mesh.txt)
[fault.sol.txt](https://github.com/MmgTools/mmg/files/9971349/fault.sol.txt)

running:

```
mmgs_O3 -ls faulty
```

will result in the following output:

```
  ## No manifold resulting situation. Exit program.
```

which is surprising since it is quite a simple example. I will tag @dapogny  since I don't have a clear idea as to why this fails.

**Comment by Algiane** [comment]
Hi @cbritopacheco , @dapogny ,

By pure coincidence I have started to look at a bug that seems similar in mmg2d (value unsnapping due to an erroneous prediction of non-manifold situation). I have fixed an unconsistency in checks in the branch `feature/fix-2d-unsnapping`. While looking if the same mistake was in mmgs/3d, I have realized that the level-set discretization in `mmgs` was outdated (I forgot to update some fixes and options done in 2D/3D because we don't have lot of users of ls discretization for 3D surface meshes). Moreover it is an almost entire copy of the 2D option so I am currently trying to refactorize both part of codes (2D and 3D surface) to avoid a useless work of maintenance.

Maybe it can worth to wait for a while to see if the bug is still present after the code refactoring and the update of the mmgs ls discretization: I will send you news and maybe leave the hand to Charles when it will be done.

Best Regards,

**Comment by cbritopacheco** [comment]
Hi again. Thank you for the message. Indeed there is a bunch of redundant code paths. To add another example to this faulty code path, MMG fails to optimize the following mesh:

```
mmgs -optim topography.mesh
```

[topography.mesh.txt](https://github.com/MmgTools/mmg/files/9980884/topography.mesh.txt)

with the following output:

```

  ## Warning: anaelt: flattened angle around ridge. Unable to split it.
  ## Error: unable to allocate larger solution.
  ## Check the mesh size or increase maximal authorized memory with the -m option.

  ## Error: anaelt: unable to allocate a new point.
  ## Check the mesh size or increase maximal authorized memory with the -m option.

  ## Unable to complete surface mesh. Exit program.

  ## Unable to split mesh-> Exiting.
  ## Error: unable to allocate adjacency table.
  ## Check the mesh size or increase maximal authorized memory with the -m option.
  Exit program.

  ## Hashing problem. Invalid mesh.

   ELAPSED TIME  55.501s
```

Unfortunately I have yet to find a workaround for this case.

**Comment by cbritopacheco** [comment]
I have renamed the issue since it might be a more general problem.

**Comment by cbritopacheco** [comment]
I have worked around this issue by choosing the Hausdorff parameter in accordance with the scale of the mesh: `-hausd 50`

**Comment by Algiane** [comment]
Hello,

Thanks for this feedback:
  - initial failure (topological issue on `fault.mesh/sol` test case) was due to the fact that we were not checking the triangle orientations when performing the level-set discretization. As your mesh contains non consistent orientations mmgs was failing. It is fixed in branch `feature/mmgs-ls-refactoring` which at the same time adds the support of `-rmc` option and multi-material mode and fix another issue in manifoldness checks. This branch will be merged in the `develop` branch once all the continuous integration tests will be checked.
  
  - on your second mesh I think that adding the `-nr` option to your command line may helps too: otherwise, Mmgs adds spurious sharp angles (ridges) in lot of areas and may fail when remeshing along these ridges because in fact the underlying surface is smooth. 
  
  Best Regards,
  Algiane

**Comment by cbritopacheco** [comment]
Hello Algiane, thank you for your detailed follow up on the bug reports! These help a ton :)
