### ISSUE TITLE
Details about the .mesh and .sol file?

### ISSUE THREAD

**Issue by ZhuShentian** [MmgTools/mmg#36]
Hi, is there any info about the details about the .mesh and .sol file?
And,what does the 'ref' param in MMG2D_Set_vertex\MMG2D_Set_triangle\MMG2D_Set_edge means?

**Comment by Algiane** [comment]
Hi,

You can find a very light documentation for the solution file in order to help users to understand how to provide an anisotropic metric: [sol file format](https://www.mmgtools.org/mmg-remesher-try-mmg/mmg-remesher-tutorials/anisotropic-metric-prescription). Providing an isotropic metric is easier, you only have to give one scalar value per node (the wanted edge size at the node).

For the mesh file, you can read the Appendix 7.2.1 of a technical report written by P. Frey:
[MEDIT : An interactive Mesh visualization Software ](https://hal.inria.fr/inria-00069921/document)

The _ref_ parameter used in the API setters correspond to the _ref_ parameter of the mesh file. It is an integer used to assign "colors" to your mesh entities. This colors are preserved during the remeshing and can be used in your solver to detecte different mesh parts, for example, to apply different boundary conditions or to have multiple materials (with different properties) in a given mesh.

Regards,

Algiane

**Comment by ZhuShentian** [comment]
Thanks a lot! Your reply does help.
