### ISSUE TITLE
Unexpected result when remeshing.

### ISSUE THREAD

**Issue by ZhuShentian** [MmgTools/mmg#40]
hi, i am using the mmg2d_o3.exe to remesh my mesh,the original mesh is shown below:
![image](https://user-images.githubusercontent.com/13469273/53412751-27e3d180-3a05-11e9-8948-ea20aabb8524.png)

after using the command line:
mmg2d_O3.exe -optim a.mesh

i got the result:
![image](https://user-images.githubusercontent.com/13469273/53412824-64173200-3a05-11e9-94ae-aa486d384ed2.png)

the mesh file:
[a.zip](https://github.com/MmgTools/mmg/files/2905400/a.zip)

Could you give me some advise about that?

**Comment by Algiane** [comment]
Hi,

The -optim option computes the size at a given point as the mean of the lengths of the edges to which belong the point. As you have very small edges in the two "spikes" of your mesh and as this edges are required, the edges sizes are propagated toward the size map in order to avoid very bad elements in the mesh.

The solution is, either to release the constraints on the boundary edges/points and to authorize the remesher to adapt the boundary (which, I know, is not always possible), either to accept to have small edges in your mesh.

Regards

Algiane

**Comment by ZhuShentian** [comment]
yes,you are right，i found two very short required edges in the input mesh and i would filter them.
thanks a lot.
