### ISSUE TITLE
Why mmgs so memory-consuming?

### ISSUE THREAD

**Issue by ZhuShentian** [MmgTools/mmg#42]
I am surface remeshing with mmgs,without a .sol file.i found that the mmgs_O3 is so memory-consuming,and the output mesh is large than the input one.The command line that i used :

mmgs_O3.exe  a.mesh

the a.mesh contains 6957 vertices and 13310 triangles,and the output mesh ,which named a.o.mesh,however, contains 905850 vertices and 1804563 triangles. I just want to remesh a surface mesh with a different size of triangular edge.
Am I doing something wrong ?

**Comment by ZhuShentian** [comment]
I found that the normalized input perform much better..

**Comment by Algiane** [comment]
Hi,

You must fit the hausdorff parameter to your test case. This parameter manage the surface remeshing in order to ensure that the boundary mesh stay sufficiently close from the ideal surface reconstructed by Mmg. Thus, it leads to refine areas of high curvature and to unrefine plane areas.

This parameter can be customized using the `-hausd` command line option followed by the wanted maximal distance between the ideal surface and its discretization. The default values is 0.01, which is suitable for a sphere with [0;1]^3 bounding box.

Regards,

Algiane

**Comment by ZhuShentian** [comment]
OK，i will keep studying this library.
Thanks a lot!
