### ISSUE TITLE
Elas doesn't exist anymore, no lagrangian movement possible

### ISSUE THREAD

**Issue by loumalouomega** [MmgTools/mmg#45]
https://github.com/MmgTools/mmg/blob/1957d7054dbebc31d786c3bbcae10329706e45bd/cmake/modules/mmg3d.cmake#L106

The ELAS library from https://github.com/SUscTools/Elas doesn't exist anymore, any place to download or alternative procedure?

**Comment by Algiane** [comment]
Hi Vicente,

The developpers of Elas have created a new repository and I forgot to update the Mmg documentation. now, the linear elasticity solver is available from [https://github.com/ISCDtoolbox/LinearElasticity](https://github.com/ISCDtoolbox/LinearElasticity).

Regards,
Algiane

**Comment by loumalouomega** [comment]
Thanks

**Comment by Foadsf** [comment]
Dear @Algiane ,

Following [this discussion](https://forum.mmgtools.org/t/compilation-with-mingw/373/11?u=foadsf), I was wondering if these optional dependencies could be added in an `include` folder using a `.gitmodules` file?

**Comment by Algiane** [comment]
Dear @Foadsf ,

Thank you for this proposition, but for now we prefer give to the user the choice of its `scotch` distribution.

Regards,
Algiane

**Comment by Foadsf** [comment]
@Algiane ,

Sure this can be optional. Also, we can use package managers. For example, I have asked for Conan and Vcpkg packages for scotch [here](https://github.com/conan-io/conan-center-index/issues/1280) and [here](https://github.com/Microsoft/vcpkg/issues/3481#issuecomment-609417545).

**Comment by prj-** [comment]
The repository you keep mentioning is not maintained anymore, so it's a rather bad idea.

**Comment by Foadsf** [comment]
@prj- Do you mean this repository

https://github.com/poulson/scotch

for scotch? it is like the first Google result. There is also this

https://github.com/OpenCMISS-Dependencies/scotch

but they both haven't been updated for the last 5-6 years. Are there any more updated clones?

**Comment by prj-** [comment]
Here is [one](https://bitbucket.org/petsc/pkg-scotch) which is actively maintained.

**Comment by Algiane** [comment]
I confirm @prj- answer: the original `scotch` repository is hosted here: git@gitlab.inria.fr:scotch/scotch.git and the last release of scotch is the 6.0.7
So you will have a more recent version of scotch using the package of @prj- link.

**Comment by Foadsf** [comment]
Dear @prj- ,

Any idea where one can open a new issue on [that repository](https://bitbucket.org/petsc/pkg-scotch/src/master/)? The [Gitlab repo](https://gitlab.inria.fr/scotch/scotch/-/tree/master) is also restricted and I can't log in with my public GitLab account. 

P.S. why anything related to INRIA must be always so messed up all the time! So many great FLOSS developed by them yet there is no consistency and proper management!

**Comment by Foadsf** [comment]
@Algiane BTW,

given this issue is mainly about the [elastic / Elas library](https://github.com/ISCDtoolbox/LinearElasticity), I have opened tickets for both Vcpkg and Conan [here](https://github.com/microsoft/vcpkg/issues/10707) and [here](https://github.com/conan-io/conan-center-index/issues/1281).

**Comment by prj-** [comment]
This repository is handled by the PETSc development team, you can open an issue on GitLab [there](https://gitlab.com/petsc/petsc). Do not bother asking there for creating SCOTCH packages with that fork, as it is only maintained for the sole purpose of the `--download-ptscotch` option in PETSc build system. Personally, I'm configuring Mmg/ParMmg with the following CMake option `-DSCOTCH_DIR=${PETSC_DIR}/${PETSC_ARCH}` and it's working flawlessly.

**Comment by Foadsf** [comment]
@prj- This scotch library, which at the moment I have no idea what it does, seems to be very popular and used in many projects, including MMG and OpenFOAM, ... I think it worth being added to some of the popular package managers. At the moment I don't know how to create Conan or Vcpkg packages. So I create the issues in the case someone knows how to do it or in the future, I stumble upon them again.

**Comment by Algiane** [comment]
Dear @Foadsf ,

Thank your for the creation of new posts.

Even if the scotch repo has been migrated on the Inria gitlab, you can still find the Scotch release on the old gforge : https://gforge.inria.fr/frs/?group_id=248 

Scotch is a graph partitionner (it allows, among other things to color a graph, in the aim to distribute it over multiple processors for example). In Mmg we use Scotch to perform node renumbering (this allow to reduce cache misses because nodes that are physically close have close indices).

I hope that it will help.

PS: Inria tries to put more and more ressources on OS projects, for example, Inria has created a support service for that, the InriaSoft team that help to the sustainability of some OS software. Of course, there is always more to do, but it is a beginning.
