### ISSUE TITLE
Remeshing computational complexity

### ISSUE THREAD

**Issue by salazardetroya** [MmgTools/mmg#65]
What's the usual cost of remeshing compared to a finite element solve? There's been a lot of work on immersed type finite element methods to avoid remeshing. I wonder if the algorithms in this library are more optimized and make the need for immersed finite element methods unnecessary. I am aware this library has been used in topology optimization. What is your experience? How does the cost of remeshing grow with the number of degrees of freedom?

**Comment by prj-** [comment]
What is the fraction of the volume to be remeshed with respect to the full domain? What are you solving with finite elements? You can look at this [document](https://tel.archives-ouvertes.fr/tel-02441844/document#page=236) (page 236) to get an element of answer, but this is highly problem-dependent. I can send you documents in private if you want some other examples.

**Comment by salazardetroya** [comment]
> What is the fraction of the volume to be remeshed with respect to the full domain? What are you solving with finite elements? You can look at this [document](https://tel.archives-ouvertes.fr/tel-02441844/document#page=236) (page 236) to get an element of answer, but this is highly problem-dependent. I can send you documents in private if you want some other examples.

It is also a topology optimization problem like the one in the document, thanks for the link. Quoting from there:

> We had difficulties in going to mesh sizes reaching the million ofvertices because the cost of remeshing becomes prohibitive.  So far, this step is performed sequentially;future works could benefit from making this step run in parallel as well.

Is the parallel version ready? It seems that the complexity of the remeshing algorithm is not good.

**Comment by prj-** [comment]
> Is the parallel version ready? It seems that the complexity of the remeshing algorithm is not good.

It's work in progress, in the sense that it's already available in the sister project [ParMmg](https://github.com/MmgTools/ParMmg), but cannot handle yet level-set and surface remeshing, which is almost mandatory for topology optimization. Should be good in [June](https://github.com/MmgTools/ParMmg/issues/4#issuecomment-590253879), hopefully.

**Comment by Algiane** [comment]
Hi @salazardetroya,

To complete the answers of @prj-: 
  * it is very hard to estimate _a priori_ the time needed for the remeshing, mostly because it is an iterative process and we can't predict the number of iterations that will be needed to converge toward a "good" mesh (_i. e._ a mesh that respect the user size map and a with elements of sufficiently good qualities). To help you: 

    * 2D remeshing is very  fast, most of time it is also the case for 3D surface remeshing, 3D volume remeshing is slower (the surface remeshing is a constraint for the volume and _vice versa_);
    * anisotropic mesh adaptation is slower than isotropic one;
    * the remeshing time increase with the size of the input mesh and the fraction of the mesh that needs  to be remeshed;
    * the number of iterations increases if the remesher has difficulties to create a good mesh: most of time it is due to bad elements stucked along the boundary. Thus, the geometric features of the mesh (number of surfaces, sharp angles, number of domains to preserve BC, etc..) impact the remeshing time;
    * the option you are using: adaptation to a sizemap, isosurface discretization or lagrangian movement;
    * _etc._

In fact, it also depends on what you are expecting. For some users, few minutes is very long because they have fast simulations, for others it doesn't matter because their simulations are time consuming...

Regarding the parallel version, it is not fully ready but we are working on it.

You are right, with our kind of algo, we don't expect to have a very good scalability and we target test cases that lasts at least few minutes. Our main aim is to provide to our users: 
  * a way to perform mesh adaptation in parallel (so they will not have to centralize their distributed mesh in order to adapt it on one proc and then to partition and redistribute it again;
  * a tool to adapt very large meshes: remeshing is a memory comsuming process and it is the memory more than the remeshing time that avoid the remeshing of large meshes. Thus, using distributed parallelization, we can hope handling meshes of billion elements.

I hope that it will help you,

Regards,

Algiane
