### ISSUE TITLE
MMGS creates surface mesh with spikes 

### ISSUE THREAD

**Issue by pareshspatel** [MmgTools/mmg#74]
mmgs -in Refine.mesh -hausd 0.05

Surface mesh has spikes in several areas. 

[Refine.zip](https://github.com/MmgTools/mmg/files/4653421/Refine.zip)

mmgs -in Cone2.mesh -nr 

This shows similar spikes, it should help you debug the issue. 

[Cone2.zip](https://github.com/MmgTools/mmg/files/4653451/Cone2.zip)

Can you please take a look and let me know the potential areas to look at? 

Thank you for your help!

**Comment by Algiane** [comment]
Hello Paresh,

I will answer in two times to make it more readable. 

## The cone test case
The cone test case works pretty well for me as soon as I help Mmg by adding the point at the cone peak (vertex of index 105) as corner in the input file. To do this you just need to add the following lines after the list of the vertices coordinates (line 125):
```
Corners
1
105
```

I try to run mmgs with different `hausd` and `hsiz` values without any issues.  For example, with `-hausd 0.01 -hsiz 0.05` I obtain the following mesh: 

![Capture d'écran 2020-05-25 17 14 25](https://user-images.githubusercontent.com/11232703/82825958-8029ad80-9eac-11ea-9dce-0c7e6b2ad7ed.png)

On this test case the usage of the hsiz parameter (or of an input metric) allows to insert points near the cone peak.

**Comment by Algiane** [comment]
## The Refine testcase

This test case is a lot more complicated for mmgs. I can propose ways of improving the mesh and ways of reflection for going further but I don't have an entirely satisfying answer.

As the mesh elements are very streched and almost degenerated, the computation of the normals may become inaccurate. There is no simple way to improve this computation from the input discretization only. In Mmg the normals are used in the model reconstruction:
  1. to reconstruct a smooth surface and to insert the new vertices along this surface (and not simply in the middle of the edges);
  2. to detect sharp angles in the geometry and to preserve it;

Thus, both features creates issues on your input mesh:
  - A way to solve the first issue (surface reconstruction) is to start by inserting points along the "flat" surface without any reconstruction. It means that new points are inserted in the middle of the input edges. Mmg doesn't allow to do that but you can use the `Refine by splitting` option of Gmsh. To have sufficiently good results with Mmg I had to run twice the `Refine by splitting` option. It allows to improve a lot the boundary representation that you will obtain with Mmg.
  - The second issue (the detection of sharp angles) is more complicated to solve:
    - If you know which edges define sharp angles, you can provide these edges to Mmg and disable the automatic detection (`-nr` option);
    - if you don't know, you will need to play with the `-ar` option to detect enough sharp angles to have a suitable surface but not too much because you will also add parasit sharp angles (which are hard to remesh). In the following I will denote the edges delimiting a sharp angle as `ridges`. The default value for the sharp angles detection is 45 (the `-val` command line argument can be use to consult the default value of the main options). If you decrease this value you will detect more sharp angles, if you increase it you will detect less sharp angles (see the red lines on the attached picture for `-ar 30`, `-ar 45`, `-ar 60`).
![Capture d'écran 2020-05-25 17 58 39](https://user-images.githubusercontent.com/11232703/82828512-81a9a480-9eb1-11ea-8cfb-57233d4e3ef9.png)

I obtain a pretty good appearance for the surface approximation using the `-ar 30` value on your intput mesh previously refined twice by Gmsh (again, see the attached picture that shows the same output mesh but wihtout and with lines). I choose this angle for the view because weirdly it was the hardest part for the remesher (missing sharp angles was leading to bump along the surface).
![Capture d'écran 2020-05-25 18 10 26](https://user-images.githubusercontent.com/11232703/82829417-7d7e8680-9eb3-11ea-9b67-aa8601bb829b.png)

There is still issues on this final mesh: it contains very bad elements along spurious sharp angles. I will try to look why the mmg operators fail along the ridges but in a few time (maybe one month). 
You can also try to clean the ridges created by Mmg by removing those one that doesn't form a loop.

I am sorry to not be more helpful for this test case.

Regards,
Algiane
